### PR TITLE
Remove the step that clones the tutorial repository.

### PR DESCRIPTION
**Pull request by xuhdev**
It is not used throughout the tutorial.

### CODE REVIEW

**Comment by ptitzler** [comment]
Okay, I believe finally understand the issue. I need to make the actual change in https://developer.ibm.com/tutorials/getting-started-with-the-ibm-code-model-asset-exchange/#tutorial-setup.
Assuming that you started here https://developer.ibm.com/tutorials/getting-started-with-the-ibm-code-model-asset-exchange and then followed the setup instructions in https://github.com/IBM/max-developer-tutorial then yes, the instruction is redundant. However, I just realized that in https://developer.ibm.com/tutorials/getting-started-with-the-ibm-code-model-asset-exchange/#tutorial-setup there is no need to clone the repository because it is not used. Not sure how we missed that. Nice catch.

**Comment by ptitzler** [comment]
The instruction in this repository is still needed for those users that land on https://github.com/IBM/max-developer-tutorial/ from a location other than https://developer.ibm.com/tutorials/getting-started-with-the-ibm-code-model-asset-exchange/. Therefore there is no need for this PR.

**Comment by xuhdev** [comment]
I'm a bit confused. Why do users who land on https://github.com/IBM/max-developer-tutorial/, for example directly, need to clone this repo?

**Comment by ptitzler** [comment]
Ah, you are right. This must be a legacy artifact.

**Review by ptitzler — APPROVED** [review]
LGTM

**Pull request merged**
